// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCECJ_mt2jdaZ4TD37RCb-wswhYt80DgoA',
    appId: '1:893061859159:web:36e658b3a674b705d56012',
    messagingSenderId: '893061859159',
    projectId: 'escan-35404',
    authDomain: 'escan-35404.firebaseapp.com',
    storageBucket: 'escan-35404.appspot.com',
    measurementId: 'G-EXNLS4JJQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoL-WBbZZ5Oi03-SJve1VAnqKyAvPLCuQ',
    appId: '1:893061859159:android:48f84b682bf5bca6d56012',
    messagingSenderId: '893061859159',
    projectId: 'escan-35404',
    storageBucket: 'escan-35404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fUPaHgP0F84hlGdFHzMoxLyQpf154Bw',
    appId: '1:893061859159:ios:1cb6bc1503d59956d56012',
    messagingSenderId: '893061859159',
    projectId: 'escan-35404',
    storageBucket: 'escan-35404.appspot.com',
    iosClientId: '893061859159-phurraqhiqno4qp9b8j0l123hmrfk8cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.escanUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9fUPaHgP0F84hlGdFHzMoxLyQpf154Bw',
    appId: '1:893061859159:ios:1cb6bc1503d59956d56012',
    messagingSenderId: '893061859159',
    projectId: 'escan-35404',
    storageBucket: 'escan-35404.appspot.com',
    iosClientId: '893061859159-phurraqhiqno4qp9b8j0l123hmrfk8cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.escanUi',
  );
}
